/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    _DocumentUploadGuide: typeof import('./../src/components/uploader/_DocumentUploadGuide.vue')['default']
    DescriptionItem: typeof import('./../src/components/design-system/DescriptionItem.vue')['default']
    DesignSystem: typeof import('./../src/components/design-system/design-system.ts')['default']
    DocumentUploader: typeof import('./../src/components/uploader/DocumentUploader.ts')['default']
    FormFacilitator: typeof import('./../src/components/core/FormFacilitator.vue')['default']
    'FormFacilitator.spec': typeof import('./../src/components/__tests__/FormFacilitator.spec.ts')['default']
    'FormFacilitator.spec.d': typeof import('./../src/components/__tests__/FormFacilitator.spec.d.ts')['default']
    'FormFacillitator.spec': typeof import('./../src/components/design-system/__tests__/FormFacillitator.spec.ts')['default']
    'FormFacillitator.spec.d': typeof import('./../src/components/design-system/__tests__/FormFacillitator.spec.d.ts')['default']
    FormGroup: typeof import('./../src/components/core/FormGroup.vue')['default']
    'FormGroup.spec': typeof import('./../src/components/design-system/__tests__/FormGroup.spec.ts')['default']
    'FormGroup.spec.d': typeof import('./../src/components/design-system/__tests__/FormGroup.spec.d.ts')['default']
    FormHeader: typeof import('./../src/components/header/FormHeader.vue')['default']
    'FormHeader.spec': typeof import('./../src/components/header/__tests__/FormHeader.spec.ts')['default']
    'FormHeader.spec.d': typeof import('./../src/components/header/__tests__/FormHeader.spec.d.ts')['default']
    FormList: typeof import('./../src/components/core/FormList.ts')['default']
    'FormList.spec': typeof import('./../src/components/__tests__/FormList.spec.ts')['default']
    GetUploadError: typeof import('./../src/components/uploader/getUploadError.ts')['default']
    InputAutoSuggest: typeof import('./../src/components/design-system/InputAutoSuggest.ts')['default']
    InputAutoSuggestDynamic: typeof import('./../src/components/design-system/InputAutoSuggestDynamic.ts')['default']
    InputCheckboxButton: typeof import('./../src/components/design-system/InputCheckboxButton.ts')['default']
    InputDate: typeof import('./../src/components/design-system/InputDate.ts')['default']
    InputDateMonth: typeof import('./../src/components/design-system/InputDateMonth.ts')['default']
    InputEmail: typeof import('./../src/components/design-system/InputEmail.ts')['default']
    InputNumber: typeof import('./../src/components/design-system/InputNumber.ts')['default']
    InputRadio: typeof import('./../src/components/design-system/InputRadio.ts')['default']
    InputSelect: typeof import('./../src/components/design-system/InputSelect.ts')['default']
    InputText: typeof import('./../src/components/design-system/InputText.ts')['default']
    'InputText.spec': typeof import('./../src/components/design-system/__tests__/InputText.spec.ts')['default']
    'InputText.spec.d': typeof import('./../src/components/design-system/__tests__/InputText.spec.d.ts')['default']
    InputTextArea: typeof import('./../src/components/design-system/InputTextArea.ts')['default']
    InputUpload: typeof import('./../src/components/design-system/InputUpload.ts')['default']
    SchemaTable: typeof import('./../src/components/design-system/SchemaTable.ts')['default']
  }
}
