/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FormHeader: typeof import('./../src/components/header/FormHeader.vue')['default']
    FormList: typeof import('./../src/components/core/FormList.ts')['default']
  }
}
